---
- name: Durcir SSH
  hosts: all
  become: yes

  vars:
    ssh_port: 2222

  tasks:
    - name: Modifier le port SSH
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Port '
        line: "Port {{ ssh_port }}"
        state: present

    - name: Interdire la connexion root via SSH
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin '
        line: "PermitRootLogin no"
        state: present

    - name: Forcer l'authentification par clé publique
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication '
        line: "PasswordAuthentication no"
        state: present

    - name: Redémarrer le service SSH
      ansible.builtin.systemd:
        name: ssh
        state: restarted